---
- name: install nginx
  apt: name=nginx state=present

- name: configure cloud.rigmaorlesoup.com
  include: cloud.yml
  notify: restart nginx

- name: configure reader.rigmaorlesoup.com
  include: reader.yml
  notify: restart nginx

- name: configure talks.rigmarolesoup.com
  include: talks.yml
  notify: restart nginx
