---
- name: pull the docker images
  docker_image: name={{ item }} state=present
  with_items:
    - nginx:stable
    - quay.io/letsencrypt/letsencrypt

- name: create shared directories on host
  file: path={{ item }} state=directory
  with_items:
    - /var/data/letsencrypt
    - /var/data/nginx

- name: create the letsencrypt data container
  docker_container:
    name: letsencrypt-data
    image: quay.io/letsencrypt/letsencrypt
    volumes:
      - /var/data/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt
    entrypoint: /bin/mkdir
    command: -p /etc/letsencrypt/webrootauth/
    detach: no

- name: create the nginx data container
  docker_container:
    name: nginx-data
    image: nginx
    volumes:
      - /var/data/nginx:/etc/nginx/conf.d
    entrypoint: /bin/true
    detach: no

- name: template nginx conf file
  template: dest="/var/data/nginx/{{ DOMAIN }}.conf" src=nginx.conf.j2

- name: check if certificates already issued
  stat: path=/var/data/letsencrypt/live/{{ DOMAIN }}/cert.pem
  register: issued_cert

- name: renew certificates
  include: renew.yml
  when: not issued_cert.stat.exists or RENEW

- name: start nginx
  docker_container:
    name: nginx
    image: nginx
    volumes_from:
      - nginx-data
      - letsencrypt-data
    links:
      - "{{ CONTAINER_NAME }}:{{ PROXY_PASS_HOST }}"
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443

