- name: destroy nginx container
  docker_container:
    name: nginx
    state: absent
    force_kill: yes

- name: get new certs (staging)
  when: not PRODUCTION
  docker_container:
    name: letsencrypt
    image: quay.io/letsencrypt/letsencrypt:latest
    recreate: yes
    ports:
      - 443:443
      - 80:80
    volumes_from:
      - letsencrypt-data
    entrypoint: certbot
    command: ["certonly", "--server", "https://acme-staging.api.letsencrypt.org/directory", "--domain", "{{ DOMAIN }}", "--authenticator", "standalone", "--email", "{{ EMAIL_ADDRESS }}", "--agree-tos"]

- name: get new certs (production)
  when: PRODUCTION
  docker_container:
    name: letsencrypt
    image: quay.io/letsencrypt/letsencrypt:latest
    recreate: yes
    ports:
      - 443:443
      - 80:80
    volumes_from:
      - letsencrypt-data
    entrypoint: certbot
    command: ["certonly", "--domain", "{{ DOMAIN }}", "--authenticator", "standalone", "--email", "{{ EMAIL_ADDRESS }}", "--agree-tos"]

- name: generate dhparams
  docker_container:
    name: tmp-dhparams
    image: nginx
    recreate: yes
    entrypoint: openssl
    command: ["dhparam", "-out", "/etc/letsencrypt/live/{{ DOMAIN }}/dhparams.pem", "2048"]
    volumes_from:
      - letsencrypt-data

- name: wait until dhparams created
  wait_for: path="/var/data/letsencrypt/live/{{ DOMAIN }}/dhparams.pem" state=present
  notify: reload nginx
