- hosts: leek
  user: root
  vars:
    USER_SSH_KEY: "{{lookup('file', '~/.ssh/leek_rsa.pub')}}"
  roles:
    - role: base
      tags: base

    - role: docker_ubuntu
      tags: docker

    - role: owncloud
      tags: owncloud

    - role: gogs
      tags: gogs

    - role: nginx
      tags: nginx
      UPSTREAM_APPS:
        - DOMAIN: cloud.rigmarolesoup.com
          CONTAINER_NAME: owncloud
          PROXY_PASS_PORT: 80

        - DOMAIN: code.rigmarolesoup.com
          CONTAINER_NAME: gogs
          PROXY_PASS_PORT: 3000

