- hosts: leek
  sudo: yes
  roles:
  - {role: base, tags: ['base']}
  - {role: docker, tags: ['docker']}
  - {role: nginx, tags: ['nginx']}
  - {role: owncloud, tags: ['owncloud']}
  - {role: ircd, tags: ['ircd']}

- hosts: radish
  sudo: yes
  roles:
  - {role: base, tags: ['base']}
