- hosts: leek
  user: root
  vars:
    USER_SSH_KEY: "{{lookup('file', '~/.ssh/leek_rsa.pub')}}"
  roles:
    - role: base
      tags: base

    - role: docker_ubuntu
      tags: docker

    - role: postgres
      tags: postgres

    - role: owncloud
      tags: owncloud
      DB_CONTAINER: postgres

    - role: gogs
      tags: gogs
      DB_CONTAINER: postgres

    - role: mattermost
      tags: mattermost
      DB_CONTAINER: postgres
      NGINX_CONF: /var/data/nginx/chat.rigmarolesoup.com.conf

    - role: nginx
      tags: nginx
      UPSTREAM_APPS:
        - DOMAIN: cloud.rigmarolesoup.com
          CONTAINER_NAME: owncloud
          PROXY_PASS_PORT: 80

        - DOMAIN: code.rigmarolesoup.com
          CONTAINER_NAME: gogs
          PROXY_PASS_PORT: 3000
          HEADERS:
            - "X-Frame-Options sameorigin"
            - "X-Xss-Protection \"1; mode=block\""
            - "X-Content-Type-Options nosniff"
            - "Content-Security-Policy \"default-src 'self'; script-src 'self' 'unsafe-eval'; img-src 'self' data: https://secure.gravatar.com; style-src 'self' 'unsafe-inline'; font-src 'self' data:; object-src 'none'\""

        - DOMAIN: chat.rigmarolesoup.com
          CONTAINER_NAME: mattermost
          PROXY_PASS_PORT: 80

