- hosts: leek
  sudo: yes
  roles:
  - {role: base, tags: ['base']}
  - {role: docker, tags: ['docker']}
  - {role: postgres, tags: ['postgres']}
  - {role: owncloud, tags: ['owncloud']}
  - {role: ircd, tags: ['ircd']}
  - {role: tinyrss, tags: ['tinyrss']}
  - {role: nginx, tags: ['nginx']}

- hosts: radish
  sudo: yes
  roles:
  - {role: base, tags: ['base']}
