- hosts: leek
  user: root
  vars:
    USER_SSH_KEY: "{{lookup('file', '~/.ssh/leek_rsa.pub')}}"
  roles:
    - {role: base, tags: ['base']}
    - role: docker_ubuntu
    - {role: owncloud, tags: ['owncloud']}
    - {role: nginx, tags: ['nginx']}

