- hosts: leek
  user: root
  vars:
    USER_SSH_KEY: "{{lookup('file', '~/.ssh/leek_rsa.pub')}}"
  roles:
    - role: base
      tags: base

    - role: docker_ubuntu
      tags: docker

    - role: postgres
      tags: postgres

    - role: owncloud
      tags: owncloud
      DB_CONTAINER: postgres

    - role: gogs
      tags: gogs
      DB_CONTAINER: postgres

    - role: mattermost
      tags: mattermost
      DB_CONTAINER: postgres
      NGINX_CONF: /var/data/nginx/chat.rigmarolesoup.com.conf

    - role: nginx
      tags: nginx
      UPSTREAM_APPS:
        - DOMAIN: cloud.rigmarolesoup.com
          CONTAINER_NAME: owncloud
          PROXY_PASS_PORT: 80

        - DOMAIN: code.rigmarolesoup.com
          CONTAINER_NAME: gogs
          PROXY_PASS_PORT: 3000

        - DOMAIN: chat.rigmarolesoup.com
          CONTAINER_NAME: mattermost
          PROXY_PASS_PORT: 80

