- hosts: leek
  sudo: yes
  user: root
  # vars_prompt:
  # - name: "user_password"
  #   prompt: "Enter a password for the user"
  #   private: yes
  #   encrypt: "sha512_crypt"
  #   confirm: yes
  #   salt_size: 7
  roles:
    - {role: base, tags: ['base']}
    - {role: docker, tags: ['docker']}
    - {role: postgres, tags: ['postgres']}
    - {role: owncloud, tags: ['owncloud']}
    - {role: tinyrss, tags: ['tinyrss']}
    - {role: nginx, tags: ['nginx']}

- hosts: radish
  sudo: yes
  roles:
  - {role: base, tags: ['base']}

- hosts: beet
  user: root
  roles:
    - {role: base, tags: ['base']}
