---
- name: reload nginx
  docker_container:
    name: nginx
    image: nginx
    recreate: yes
    volumes_from:
      - nginx-data
      - letsencrypt-data
    links: "{{ UPSTREAM_APPS|map(attribute='CONTAINER_NAME')|list }}"
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
