---
- name: set up the mattermost db
  include: db.yml

- name: clone the mattermost repo
  git: 
    repo: https://github.com/mattermost/mattermost-docker.git
    dest: /tmp/mattermost

- name: build the image
  docker_image:
    path: /tmp/mattermost/app
    dockerfile: /tmp/mattermost/app/Dockerfile
    name: sw00/mattermost
    repository: sw00/mattermost

- name: create shared directories on host
  file: path={{ item }} state=directory
  with_items:
    - /var/data/mattermost/config
    - /var/data/mattermost/data

- name: create the mattermost data container
  docker_container:
    name: mattermost-data
    image: sw00/mattermost
    volumes:
      - /var/data/mattermost/config:/mattermost/config:rw
      - /var/data/mattermost/data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /bin/true
    detach: no

- name: run the container
  docker_container:
    name: mattermost
    image: sw00/mattermost
    recreate: yes
    volumes_from:
      - mattermost-data
    links:
      - "{{ DB_CONTAINER }}:db"
  notify: enable websockets

