---
- apt: upgrade=dist

- name: install docker package
  apt: update_cache=yes name=docker.io state=latest
  notify: add user to docker group

- name: install docker-py #v1.1.0 beca
  pip: name=docker-py version=0.7.2 state=present

- name: install docker-compose
  pip: name=docker-compose state=latest

- name: install requests
  pip: name=requests state=latest
