---
- name: set the hostname
  hostname: name="{{inventory_hostname}}"

- name: edit localhost loopback in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ^127\.0\.0\.1
    line: "127.0.0.1 localhost {{inventory_hostname}}"

- name: update apt-cache
  apt: update_cache=yes

- name: add authorized key
  authorized_key: user=root key="{{USER_SSH_KEY}}" exclusive=yes

- name: install python
  apt: name=python state=present

- name: install pip
  apt: name=python-pip state=present

- name: install git
  apt: name=git state=present

- name: create /var/data
  file: path=/var/data state=directory
