---
- name: update apt-cache
  apt: update_cache=yes

- name: ensure user account exists
  user: name=sett groups='sudo' append=yes shell=/bin/bash state=present

- name: install python
  apt: name=python state=present

- name: install pip
  apt: name=python-pip state=present

- name: install docker
  pip: name=docker-py state=present

- name: install docker-compose
  pip: name=docker-compose state=present

- name: install git
  apt: name=git state=present
