---
- name: pull docker image
  docker_image: name=postgres:9.4 state=present

- name: create data container
  docker:
    name: postgres-data
    image: postgres:9.4
    volumes:
      - /var/lib/postgresql/data
    state: present

- name: run postgres container
  docker:
    image: postgres:9.4
    name: postgresdb
    volumes_from: postgres-data
    state: running
    env:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
