---
- name: pull postgres image
  docker_image: name=postgres state=present

- name: create postgres data container
  docker_container:
    name: "{{ CONTAINER_NAME }}-data"
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    entrypoint: /bin/true

- name: start postgres container
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: postgres
    recreate: yes
    volumes_from:
      - "{{ CONTAINER_NAME }}-data"
    env:
      POSTGRES_USER: "{{ POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"

