---
- name: pull docker image
  docker_image: 
    docker_api_version: '1.20'
    name: postgres
    tag: 9.4
    path: .

- name: create data container
  docker:
    docker_api_version: '1.20'
    name: postgres-data
    image: postgres:9.4
    volumes:
      - /var/lib/postgresql/data
    state: present

- name: run postgres container
  docker:
    docker_api_version: '1.20'
    image: postgres:9.4
    name: postgresdb
    volumes_from: postgres-data
    state: running
    env:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
