---
# back up and tar owncloud data and psqldump
# then upload to s3 bucket

- name: install dependencies
  pip: name=boto state=present

- name: ensure backup directory exists on host
  file: path={{ HOST_BACKUP_DIR }} state=directory

- name: create the data backup
  docker_container:
    name: backup-owncloud
    image: owncloud
    entrypoint: /bin/tar
    command: ["cvf", "/backup/owncloud_backup_{{ ansible_date_time.date }}.tgz", "/var/www/html"]
    detach: no
    volumes_from: owncloud-data
    volumes:
      - "{{ HOST_BACKUP_DIR }}:/backup"
  notify: remove owncloud backup container

- name: save data backup to Amazon S3
  s3:
    object: "/backups/owncloud_backup_{{ ansible_date_time.date }}.tgz"
    src: "{{ HOST_BACKUP_DIR }}/owncloud_backup_{{ ansible_date_time.date }}.tgz"
    bucket: rigmarolesoup
    region: eu-west-1
    mode: put
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"

- name: remove data backup to save space
  file:
    path: "{{ HOST_BACKUP_DIR }}/owncloud_backup_{{ ansible_date_time.date }}.tgz"
    state: absent

- name: create the db backup
  docker_container:
    name: backup-postgres
    image: postgres
    entrypoint: pg_dump
    command: ["owncloud", "-h", "db", "-U", "postgres", "-f", "/backup/postgres_backup_{{ ansible_date_time.date }}.bak"]
    detach: no
    volumes_from: postgres-data 
    volumes:
      - "{{ HOST_BACKUP_DIR }}:/backup"
    links:
      - postgres:db
  notify: remove postgres backup container

- name: save db backup to Amazon S3
  s3:
    object: "/backups/postgres_backup_{{ ansible_date_time.date }}.bak"
    src: "{{ HOST_BACKUP_DIR }}/postgres_backup_{{ ansible_date_time.date }}.bak"
    region: eu-west-1
    bucket: rigmarolesoup
    mode: put
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"

- name: remove db backup to save space
  file:
    path: "{{ HOST_BACKUP_DIR }}/postgres_backup_{{ ansible_date_time.date }}.bak"
    state: absent

