---
- name: pull postgres image
  docker_image: name=postgres state=present

- name: pull owncloud image
  docker_image: name=owncloud state=present
    
- name: create postgres data container
  docker_container:
    name: postgres-data
    image: postgres
    volumes:
      - /dbdata

- name: start postgres container
  docker_container:
    name: postgres
    image: postgres
    volumes_from:
      - postgres-data
    env:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

- name: create owncloud data container
  docker_container:
    name: owncloud-data
    image: owncloud:9
    volumes:
      - /var/www/html

- name: start owncloud container
  docker_container:
    name: owncloud
    image: owncloud:9
    volumes_from:
      - owncloud-data
    links:
      - postgres:db

- name: backup owncloud
  include: backup.yml
  tags: backup
  when: BACKUP|default(false)

- name: restore owncloud
  include: restore.yml
  tags: restore
  when: RESTORE|default(false)
