---
- name: pull owncloud image
  docker_image: name=owncloud state=present
    
- name: create owncloud data container
  docker_container:
    name: owncloud-data
    image: owncloud
    volumes:
      - /var/www/html
    entrypoint: /bin/true

- name: start owncloud container
  docker_container:
    name: owncloud
    image: owncloud:9
    recreate: yes
    volumes_from:
      - owncloud-data
    links:
      - "{{ DB_CONTAINER }}:db"
