---
- name: build the image
  docker_image: name=owncloud:8.1 state=present

- name: create data container
  docker:
    name: owncloud-data
    image: owncloud:8.1
    volumes:
      - /var/data

- name: run owncloud container
  docker:
    name: owncloud
    image: owncloud:8.1
    ports: "127.0.0.1:9000:80"
    links:
      - "postgresdb:db"
    volumes_from: owncloud-data
    state: running
